### PR TITLE
Fix navbar

### PR DESCRIPTION
**Pull request by prostoleo**
Change Navbar component according to design. Update tailwind config with necessary new colors.

### CODE REVIEW

**Review by darioguarascio — CHANGES_REQUESTED** [review]
@prostoleo as tabbing, i would use space 2 if possible, instead of tab

**Comment by prostoleo** [comment]
Can i create .prettierrc for this?

**Comment by darioguarascio** [comment]
absolutely!

**Comment by prostoleo** [comment]
added .prettierrc

**Review by darioguarascio — APPROVED** [review]

**Pull request merged**
